### ISSUE TITLE
Guzzle Version issue

### ISSUE THREAD

**Issue by bostin** [criteo/criteo-api-marketingsolutions-php-sdk#6]
https://github.com/criteo/criteo-api-marketingsolutions-php-sdk/blob/a4a59d1700020af7d1b8c4fed76fee0cd4048f56/lib/Api/GatewayApi.php#L351C17-L351C17

GuzzleHttp\Utils added at `guzzlehttp/guzzle: 6.5.3`

please upgrade guzzlehttp/guzzle to ^6.5.3

**Comment by gturri** [comment]
Fixed
